### ISSUE TITLE
[Feature Request] Make board movevent slower on higher zooms

### ISSUE THREAD

**Issue by 3DanielK** [Nimi142/MineSweeperHome#4]
Right now, when the player moves across the board, the movement speed is (seemingly) the same, regardless of the current zoom level.
A sufficiently fast movement speed on low zoom levels would be too fast on high zoom levels. Therefore, I suggest that the movement speed will depend on the zoom level so that, when moving, the part of the screen that gets revealed (or hidden) per unit time is constant.

**Comment by Nimi142** [comment]
Daniel, lol.
Check the repository.
